---
- name: Set records variable to generate zone file
  ansible.builtin.set_fact:
    records: >-
      {{ records | default({})
        | combine({
              item.value.tenant.name: records[item.value.tenant.name] | default([])
              + [{
                 'address': item.value.address | ansible.netcommon.ipaddr('address'),
                 'dns_name': item.value.dns_name | regex_replace('\.' + domain + '$', ''),
                 'description': item.value.description,
                 'subnet': item.value.address | ansible.netcommon.ipaddr('subnet')
              }]
          })
      }}
  loop: "{{ gather_activate_ips }}"
  when:
    - "'tenant' in item.value"
    - item.value.tenant != none
    - item.value.dns_name | length >= 1

- name: Generate a forward zone file
  ansible.builtin.template:
    src: templates/bind_forward_config.j2
    dest: "{{ bind_config_dir }}/{{ item.key }}.db"
    mode: "0644"
  loop: "{{ records | dict2items }}"
  notify:
    - reload bind
